spring.application.name=SunHarvestBackend


################
## DATASOURCE ##
################
spring.datasource.db-kind=oracle
spring.datasource.username=RM562700
spring.datasource.password=090805
spring.datasource.url=jdbc:oracle:thin:@oracle.fiap.com.br:1521:orcl
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

spring.jpa.hibernate.ddl-auto=create-drop

spring.hibernate-orm.database.generation=validate
spring.hibernate-orm.log.sql=true
spring.hibernate-orm.jdbc.fetch-size=100

###########
## JWT   ##
###########
jwt.secret=c3VuaGFydmVzdC1qd3Qtc2VjcmV0LWtleS1jaGFuZ2UtaW4tcHJvZHVjdGlvbg==
jwt.expiration=86400000